root: true
env:
  es6: true
  node: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:prettier/recommended
parserOptions:
  ecmaVersion: 2017
plugins:
  - import
  - unicorn
rules:
  curly: error
  import/no-extraneous-dependencies:
    - error
    - devDependencies: ["tests*/**", "scripts/**"]
  no-else-return: error
  no-inner-declarations: error
  no-unneeded-ternary: error
  no-useless-return: error
  no-var: error
  one-var:
    - error
    - never
  prefer-arrow-callback: error
  prefer-const: error
  react/display-name: off
  react/no-deprecated: off
  react/prop-types: off
  strict: error
  symbol-description: error
  yoda:
    - error
    - never
    - exceptRange: true
  unicorn/new-for-builtins: error
  unicorn/prefer-includes: error
